CREATE TABLE nePRODUCT (ID INT PRIMARY KEY, PRODUCT_NAME VARCHAR(25));
INSERT INTO nePRODUCT (ID,PRODUCT_NAME) VALUES (1,'neHoney');
INSERT INTO nePRODUCT (ID,PRODUCT_NAME) VALUES (2,'neAlmond');
INSERT INTO nePRODUCT (ID,PRODUCT_NAME) VALUES (3,'nelalala');
